name: Javadoc CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  javadoc:
    if: ${{ github.repository_owner == 'lucfr1746' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package javadoc:javadoc -X

      - name: List contents of target/site
        run: ls -R LLibrary/target/site || echo "No site directory found"

      - name: Copy Javadoc artifacts
        run: |
          mkdir -p artifacts/LLibrary-api
          if [ ! -d "LLibrary/target/site/apidocs" ]; then
            echo "Javadoc not found at expected location!"
            exit 1
          else
            cp -r LLibrary/target/site/apidocs/* artifacts/LLibrary-api/
          fi

      - name: Deploy Javadoc 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: false
          folder: artifacts
